spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: r00t
    url: jdbc:mem:testSpring
    username: root
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
      